### ISSUE TITLE
Not enough Feedback

### ISSUE THREAD

**Issue by tamueller** [tamueller/memrise-flip-cards#1]
Most important issue now is feedback from users. Does it work in firefox?
Does it work on chrome/firefox in mac?
This can only be solved by _you_

**Comment by azkore** [comment]
Just installed and tried the extension, it doesn't work for me in the latest chrome (Version 68.0.3440.106 (Official Build) (64-bit))

These messages from console look relevant:

raven.js:58 jQuery.Deferred exception: Cannot read property 'load' of undefined TypeError: Cannot read property 'load' of undefined
    at eval (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=0629cf93-79eb-4b49-9fe3-780500fc24eb:27:33)
    at HTMLDocument.eval (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=0629cf93-79eb-4b49-9fe3-780500fc24eb:33:6)
    at t (https://static.memrise.com/dist/js/libs-a4fd8e8bf113.js:1:29183)
    at e (https://static.memrise.com/dist/js/libs-a4fd8e8bf113.js:1:29485)
    at t (https://static.memrise.com/dist/js/libs-a4fd8e8bf113.js:1:436026) undefined
t.(anonymous function) @ raven.js:58
S.Deferred.exceptionHook @ jquery.js:3818
e @ jquery.js:3606
t @ raven.js:445
setTimeout (async)
(anonymous) @ raven.js:1194
(anonymous) @ jquery.js:3640
c @ jquery.js:3268
add @ jquery.js:3327
(anonymous) @ jquery.js:3660
Deferred @ jquery.js:3751
then @ jquery.js:3645
S.fn.ready @ jquery.js:3840
(anonymous) @ userscript.html?id=0629cf93-79eb-4b49-9fe3-780500fc24eb:18
(anonymous) @ VM7961:2
(anonymous) @ userscript.html?id=0629cf93-79eb-4b49-9fe3-780500fc24eb:2
(anonymous) @ userscript.html?id=0629cf93-79eb-4b49-9fe3-780500fc24eb:3
(anonymous) @ userscript.html?id=0629cf93-79eb-4b49-9fe3-780500fc24eb:119
(anonymous) @ userscript.html?id=0629cf93-79eb-4b49-9fe3-780500fc24eb:121
(anonymous) @ VM7961:2
b @ VM7961:1
E_u @ VM7961:3
t @ VM8087:64
ka @ VM8087:62
create @ VM8087:73
e @ VM8087:17
setTimeout (async)
(anonymous) @ VM7961:2
y.(anonymous function) @ VM7961:8
(anonymous) @ VM8087:17
runListeners @ VM8087:17
Ua @ VM8087:17
run @ VM8087:18
(anonymous) @ VM8087:75
(anonymous) @ VM7961:2
b @ VM7961:1
(anonymous) @ VM8087:75
(anonymous) @ VM8087:75
TM_back @ VM8087:76
(anonymous) @ VM8087:76
(anonymous) @ VM7961:2
exec_fn @ VM7961:1
(anonymous) @ VM7961:11
R @ VM7961:10
e @ content.js:6
send @ content.js:8
next @ content.js:13
(anonymous) @ content.js:28
(anonymous) @ content.js:24
sendResponseAndClearCallback @ VM7957 extensions::messaging:419
messageListener @ VM7957 extensions::messaging:451
EventImpl.dispatchToListener @ VM7950 extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ VM7956 extensions::utils:138
EventImpl.dispatch_ @ VM7950 extensions::event_bindings:387
EventImpl.dispatch @ VM7950 extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ VM7956 extensions::utils:138
dispatchOnMessage @ VM7957 extensions::messaging:392
raven.js:449 Uncaught TypeError: Cannot read property 'load' of undefined
    at eval (userscript.html?id=0629cf93-79eb-4b49-9fe3-780500fc24eb:27)
    at HTMLDocument.eval (userscript.html?id=0629cf93-79eb-4b49-9fe3-780500fc24eb:33)
    at t (jquery.js:3534)
    at e (jquery.js:3602)
    at t (raven.js:445)
